version: '3'
services:
    mysql:
        image: mysql
        environment:
            MYSQL_USER: evans
            MYSQL_PASSWORD: evans
            MYSQL_DATABASE: nas
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - /srv/Owncloud/data:/data
        expose:
            - "3306"
        container_name: mysql
    redis:
        image: redis
        expose:
            - "6379"
        container_name: redis
