version: '3'
services:
    mysql:
        image: mysql
        environment:
            MYSQL_USER: evans
            MYSQL_PASSWORD: evans
            MYSQL_DATABASE: nas
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - /srv/Owncloud/data:/data
        expose:
            - "3306"
        container_name: mysql
    redis:
        image: redis
        expose:
            - "6379"
        container_name: redis
    owncloud:
        image: owncloud
        expose:
            - "80"
        volumes:
            - ./owncloud/config:/var/www/html/config
            - ./owncloud/data:/var/www/html/data
        links:
            - mysql
            - redis
        container_name: owncloud
    nginx:
        image: nginx
        volumes:
            - /srv/Owncloud:/var/www/html
        links:
            - owncloud
        ports:
            "80:80"
        container_name: nginx
